### ISSUE TITLE
Stream

### ISSUE THREAD

**Issue by alifeunfolds** [DaewoongP/dw#5]
**라즈베리파이에서 카메라에서 받은 영상 전송**
- [ ] mpeg-dash
- [x] vlc
- [ ] hls
- [ ] opencv -> dash

**Comment by leejihown** [comment]
vlc 스트리밍 확인 했습니다. 스트리밍 스로토콜은 HTTP기반이로 돌아가지만 다른 프로토콜도 지원하며 안드로이드 앱을 통해서 스트리밍을 해 본 결과 지연시간이 2초에서 3초정도가 있고 네트웨크 속도에 따라 스트리밍 속도가나 지연이 영향을 많이 받습니다. H264 형식을 파일을 사용했으며 일정 시간 이후에 작동이 정지 됩니다.

**Comment by alifeunfolds** [comment]
# 안드로이드에서 mpeg-dash 재생
https://developer.android.com/guide/topics/media/exoplayer
https://codelabs.developers.google.com/codelabs/exoplayer-intro/#0
https://github.com/google/ExoPlayer
http://google.github.io/ExoPlayer/

**Comment by leejihown** [comment]
http://www.rasplay.org/?p=6257

**Comment by alifeunfolds** [comment]
[Docker 배포](https://subicura.com/2017/02/10/docker-guide-for-beginners-create-image-and-deploy.html)
