### ISSUE TITLE
[안드로이드] 버튼 구현

### ISSUE THREAD

**Issue by alifeunfolds** [DaewoongP/dw#9]
- 팬/틸트 수동 조작 구현

**Comment by alifeunfolds** [comment]
[rendering error](https://stackoverflow.com/questions/44449275/failed-to-load-appcompat-actionbar-with-unknown-error-in-android-studio)

**Comment by DaewoongP** [comment]
[rendering error "KR"](https://nachoi.github.io/studynote/2018/06/17/Android-Studio-Render-Problem.html)

**Comment by DaewoongP** [comment]
[gradle 사용법](http://wimir-dev.tistory.com/7)

**Comment by alifeunfolds** [comment]
mqtt://q.safecorners.io:1883

**Comment by alifeunfolds** [comment]
[MQTT Android Client Tutorial](https://wildanmsyah.wordpress.com/2017/05/11/mqtt-android-client-tutorial)

**Comment by DaewoongP** [comment]
[MQTT android](http://devlab.neonkid.xyz/posts/android/Android-%EC%97%90%EC%84%9C-MQTT-%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%B4%EB%B3%B4%EC%9E%90.html)

**Comment by DaewoongP** [comment]
[hive mqtt 코드 사용법](https://www.youtube.com/watch?v=gae05UKmXKc)

**Comment by DaewoongP** [comment]
[hive mqtt 웹페이지](https://www.hivemq.com/blog/mqtt-client-library-enyclopedia-paho-android-service)

**Comment by alifeunfolds** [comment]
[Paho Mqtt Android 예제](https://github.com/eclipse/paho.mqtt.android)
